services:
  - type: web
    name: niuniu-auto-order
    runtime: docker
    repo: https://github.com/morerre/niuniu-qb   # 替换为你的真实仓库地址
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.13